[package]
name = "comet_ir"
version = "0.1.0"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
petgraph = "0.4.13"
cranelift-entity = "0.40.0"
# TODO: rust-typed-arena
comet_parser = { path = "../parser" }

[dev-dependencies]
pretty_assertions = "0.6"
